default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['PGHOST'] %>
  username: postgres
  pool: 5

development:
  <<: *default
  database: happy_nel_development

test:
  <<: *default
  database: happy_nel_test

production:
  <<: *default
  database: happy_nel_production
  username: happy_nel
  password: <%= ENV['HAPPY_NEL_DATABASE_PASSWORD'] %>